### ISSUE TITLE
Latest API checkin causing Cannot find module errro

### ISSUE THREAD

**Issue by erictice** [hygieia/api#203]
**[error] Error: Cannot find module '@angular-devkit/build-angular/package.json'**
Require stack:
- /usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/models/architect-command.js
- /usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/commands/serve-impl.js
- /usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/utilities/json-schema.js
- /usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/models/command-runner.js
- /usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (/usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:42:41)
    at ServeCommand.initialize (/usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/models/architect-command.js:139:55)
    at async ServeCommand.validateAndRun (/usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/models/command.js:124:9)
    at async Object.runCommand (/usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/models/command-runner.js:198:24)
    at async default_1 (/usr/local/Cellar/angular-cli/10.1.6/libexec/lib/node_modules/@angular/cli/lib/cli/index.js:59:31)

**Affects:** \<api-version-number>.

---

**Comment by erictice** [comment]
Was an angular issue on Mac
